/* SPDX-License-Identifier: GPL-3.0-only */
/* ABK_KSU_SANDBOX_V1 */
#ifndef __KSU_ABK_SANDBOX_LSM_BUILD_CONFIG_H
#define __KSU_ABK_SANDBOX_LSM_BUILD_CONFIG_H

#ifndef ABK_KSU_RUNTIME_TAIL_SOURCE_VERIFIED
#define ABK_KSU_RUNTIME_TAIL_SOURCE_VERIFIED 0
#endif

#if ABK_KSU_RUNTIME_TAIL_SOURCE_VERIFIED != 0 && \
	ABK_KSU_RUNTIME_TAIL_SOURCE_VERIFIED != 1
#error "ABK_KSU_RUNTIME_TAIL_SOURCE_VERIFIED must be 0 or 1"
#endif

#if ABK_KSU_RUNTIME_TAIL_SOURCE_VERIFIED && defined(CONFIG_KSU_SUSFS) && \
	!defined(CONFIG_KSU_TRACEPOINT_HOOK) && \
	!defined(CONFIG_KSU_MANUAL_HOOK) && \
	!defined(CONFIG_KSU_MANUAL_HOOK_AUTO_SETUID_HOOK) && \
	!defined(CONFIG_KSU_MANUAL_HOOK_AUTO_INITRC_HOOK)
#define ABK_KSU_ALLOW_RUNTIME_KSU_TAIL 1
#else
#define ABK_KSU_ALLOW_RUNTIME_KSU_TAIL 0
#endif

#endif /* __KSU_ABK_SANDBOX_LSM_BUILD_CONFIG_H */
